### PR TITLE
Small fix to compile with gcc 4.9

### PR DESCRIPTION
**Pull request by slosar**

### CODE REVIEW

File: likely/Random.h [hunk 1]
```diff
@@ -11,6 +11,7 @@
 
 #include <cstddef>
 #include <vector>
+#include <stdint.h>
```
Comment (dkirkby) [inline likely/Random.h]: Can you check if <stdint> works also, since the .h is normally not required.

Comment (slosar) [inline likely/Random.h]: Actually, on my machine you *do* need .h. Weird, isn't it?

-- 
anže

Comment (dkirkby) [inline likely/Random.h]: Sorry, I meant `<cstdint>`.  You are generally supposed to include `<cxxx>` instead of `<xxx.h>` in C++, with the only difference being that the C++ version wraps everything in a namespace, to avoid polluting the global namespace.

Comment (slosar) [inline likely/Random.h]: Uhm, it works but requires compiler option to enable c++11, e.g.

/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file 
requires compiler and library support for the ISO C++ 2011 standard. This 
support is currently experimental, and must be enabled with the -std=c++11 
or -std=gnu++11 compiler options.
  #error This file requires compiler and library support for the \
...



-- 
anže
